name: yaml_localizations
description: A minimal YAML localization package for Flutter built on LocalizationsDelegate.
version: 0.1.0+2
homepage: https://github.com/erf/yaml_localizations

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  yaml: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

