name: yaml_localizations
description: A minimal YAML localization package built on LocalizationsDelegate.
version: 1.4.0
homepage: https://github.com/erf/yaml_localizations

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

